### ISSUE TITLE
Extra files are installed

### ISSUE THREAD

**Issue by slozovsky** [noxdafox/clipspy#23]
Setup.py installs files that are not needed for package operation:

data_files=[('lib', ['lib/clips.c', 'lib/clips.cdef'])],

**Comment by noxdafox** [comment]
Hello,

it is necessary to include the library files in the distribution as the compilation happens during installation. If the two above files would not be included, installation would fail.

**Comment by slozovsky** [comment]
Ok. No problem. Our company packaging system requires RPMs, so I did such packaging and excluded these files. Everything worked (with the line commented out) and 'lib/clips.c', 'lib/clips.cdef' are not installed on the target which is nice. But if they are needed for some other workflows - it's ok.

RPMs are built through your Makefile.

**Comment by noxdafox** [comment]
Currently, `clipspy` can be installed in two ways:

As Python package via `pip` if the CLIPS shared libraries and headers are already present within the target system. This works out of the box for example on Debian and derivates. In Windows, `clipspy` is distributed as Python wheel which is a binary package including the compiled bindings together with CLIPS as static library.
The Python package needs to ship all files which are needed for compiling the bindings on the target system. That's why I ended up using the `data_files` field in the setup file, there was no other way to package those files together with the rest.

Through the `Makefile` which I later included to help all the people which were trying to install `clipspy` on a non Debian distribution/Windows. This is more of a hack rather than a proper installation script but it got quite few people through.

I am not familiar with RPM packages but if they are similar to `.deb` packages it will indeed work because the binaries are compiled during the build process and not during the installation one. Therefore, you can safely remove them as if you ship a binary the `.c` and `.cdef` files are not necessary.

**Comment by slozovsky** [comment]
Yes, .rpm (RedHat, CentOS, etc.) is similar to .deb
